spring:
  application:
    name: ad-campaign-tool
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    name: ad-management
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/admanagement
    username:
    password:
    driverClassName: org.postgresql.Driver
  server:
    error:
      include-message: always
      include-binding-errors: always
      include-exception: false
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#      mail.debug: true
#  logging:
#    level:
#      org.springframework.amqp: DEBUG
#      org.springframework.messaging: DEBUG
#      com.rabbitmq: DEBUG
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem